name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  # Backend
  backend-test:
    name: Backend Test
    runs-on: ubuntu-latest

    steps:

      # Get code
      - name: Checkout
        uses: actions/checkout@v4

      # Install uv
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      
      # Create virtual environment
      - name: Create virtual environment
        run: uv venv

      # Install Python
      - name: Setup Python
        run: uv python install 3.11

      # Install backend dependencies
      - name: Install Dependencies
        working-directory: Backend
        run: |
          uv pip install -r requirements.txt

      # Check Python syntax
      - name: Check Python
        working-directory: Backend
        run: |
          uv run python -m compileall .


  # Frontend
  frontend-test:
    name: Frontend Test
    runs-on: ubuntu-latest

    steps:

      # Get code
      - name: Checkout
        uses: actions/checkout@v4

      # Install Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Install frontend dependencies
      - name: Install Dependencies
        working-directory: frontend
        run: |
          npm ci

      # Build Next.js
      - name: Build Frontend
        working-directory: frontend
        run: |
          npm run build